---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/rewrite-target: /
    name: {{ .ServiceName }}
    labels:
      app: {{ .ServiceName }}
  spec:
    backend:
      serviceName: {{ .ServiceName }}
      servicePort: 80
    rules:
    - host: {{ .ServiceName }}.local
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .ServiceName }}
            servicePort: 80